knp_paginator:
    page_range: 5                       # Nombre de pages à afficher dans la pagination
    default_options:
        page_name: page                 # Nom du paramètre de page dans l'URL
        sort_field_name: sort           # Nom du paramètre de tri
        sort_direction_name: direction  # Nom du paramètre de direction de tri
        distinct: true                  # Assure l'unicité des résultats
        filter_field_name: filterField  # Nom du paramètre de filtre
        filter_value_name: filterValue  # Nom de la valeur de filtre
    template:
        pagination: 'pagination/pagination.html.twig'  # Template personnalisé
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
